# Generated by Django 2.2.11 on 2020-04-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.BooleanField()),
                ('febreM', models.BooleanField()),
                ('febreA', models.BooleanField()),
                ('tosseP', models.BooleanField()),
                ('tosseS', models.BooleanField()),
                ('fdeAr', models.BooleanField()),
                ('dparaResp', models.BooleanField()),
                ('pGastrico', models.BooleanField()),
                ('diarreia', models.BooleanField()),
                ('infectado', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
