# Generated by Django 2.2.11 on 2020-04-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='diarreia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dparaResp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fdeAr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='febreA',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='febreM',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='infectado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pGastrico',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tosseP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tosseS',
            field=models.IntegerField(default=0),
        ),
    ]
